### ISSUE TITLE
make image bigger?

### ISSUE THREAD

**Issue by ccstoragedrivez** [navaneethkm004/Discord-Gamebuay#2]
is it possible to make the GBA resolution / image bigger? right now, its at 240x160 and id like to make it bigger

**Comment by navaneethkm004** [comment]
Go [here](https://github.com/navaneethkm004/Discord-Gamebuay/blob/main/src/emulator/GameBoy.js#L28) and change the values according to the aspect ratio 10:9.
Now go [here](https://github.com/navaneethkm004/Discord-Gamebuay/blob/main/src/emulator/GameBoy.js#L78) and change the value to the first value you selected [here](https://github.com/navaneethkm004/Discord-Gamebuay/blob/main/src/emulator/GameBoy.js#L28). Now we changed Gameboy emulator's size!

Now go [here](https://github.com/navaneethkm004/Discord-Gamebuay/blob/main/src/emulator/NES.js#L32) and [here](https://github.com/navaneethkm004/Discord-Gamebuay/blob/main/src/emulator/NES.js#L33) and change the values in the aspect ratio 16:15 ratio.

**Comment by ccstoragedrivez** [comment]
what about for GBA?
